config/routes.rb
Rails.application.routes.draw do
  get 'neighborhood/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :neighborhood, only: [:index]
  resources :tasks, only: [:index]
  resources :activities, only: [:create]
  resources :chatrooms, only: [:show, :index, :create] do
    resources :messages, only: :create
  end

  scope module: :garden do
    resources :plants do
      member do
        patch 'upvote'
        patch 'dislike'
      end
    end

    get '/communities', to: 'communities#index'
    get '/communities/classement', to: 'communities#classement'
  end
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :plant
  belongs_to :task

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :plant
  belongs_to :task

  scope :before_date, ->(date) { where("created_at < ?", date) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  belongs_to :plant_information

  has_many :activities
  has_many :tasks, through: :plant_information

  has_one_attached :photo
  validates :age_in_days, presence: true
  # validates :photo, presence: true
end

app/models/plant_information.rb
class PlantInformation < ApplicationRecord
  has_many :plants
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :plant_information

  has_many :activities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :plants
  has_many :activities, through: :plants
  has_many :messages

  has_one_attached :photo

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def create
    activity = Activity.new(activity_params)
    plant = Plant.find(params[:activity]["plant_id"])
    task = Task.find(params[:activity]["task_id"])
    activity.done = true
    activity.plant = plant
    activity.task = task
    activity.save!

    current_user.score += task.score
    current_user.save!
    # redirect_to tasks_path
  end

  private

  def activity_params
    params.require(:activity).permit(:plant_id, :task_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
  
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

    def index
        messages = Message.where(user_id: current_user)
        chats = []
        messages.each do |message|
           chats << message.chatroom
        end
        @chatrooms = chats.uniq
    end

    def show
        @chatroom = Chatroom.find(params[:id])
        @message = Message.new chatroom: @chatroom
        @messages = @chatroom.messages.includes(:user)
    end

    def create
      @chatroom = Chatroom.new(chatroom_params)
      if @chatroom.save
        redirect_to chatroom_path(@chatroom)
      else
        render :new
      end
    end

    def chatroom_params
        params.require(:chatroom).permit(:name)
    end

end

app/controllers/garden/communities_controller.rb
module Garden
  class CommunitiesController < ApplicationController
    def index
      @plants = Plant.where.not(user_id: current_user.id)
      @now = Time.now
      @chatroom = Chatroom.new

      # my_chatrooms = Message.all.where(user_id: current_user.id).select(:chatroom_id).distinct
      # my_chatrooms.each do

      # end
      # raise
    end

    def classement
      @order = User.order(score: :desc)
      @podium = @order[0..2]
      @user = current_user
      @ranking = @order[3..-1]
    end
  end
end

app/controllers/garden/plants_controller.rb
module Garden
  class PlantsController < ApplicationController
    def show
      @plant = Plant.find(params[:id])
      @samePlant = Plant.where(plant_information_id: @plant.plant_information_id)
    end

    def index
      @user_plants = Plant.where(user_id: current_user.id)
      # @creation_date = @user_plant[].created_at.strftime("%d %b. %Y")
      @now = Time.now
    end

    def new
      @plant = Plant.new
      @plant_infos = []
      PlantInformation.all.select(:name).each do |_plantinfo|
        @plant_infos << _plantinfo.name
      end
    end

    def create
      obtention_date = params[:plant][:age_in_days]
      obtention_date = obtention_date.split("-")
      age_in_days = (Date.today - Date.new(obtention_date[0].to_i, obtention_date[1].to_i, obtention_date[2].to_i)).to_i
      @plant = Plant.new(plants_params)
      @plant.user = current_user
      @plant_information = PlantInformation.find_or_create_by(name: params["plant"]["plant_information"])
      @plant.plant_information = @plant_information
      @plant.age_in_days = age_in_days

      if @plant.save
        redirect_to plants_path
      else
        render :new
      end
    end

    def upvote
      @plant = Plant.find(params[:id])
      @plant.like_number += 1
      @plant.save!
      @plant.user.score += 1
      @plant.user.save!
      # redirect_to communities_path
    end

    def dislike
      @plant = Plant.find(params[:id])
      @plant.like_number -= 1
      @plant.save!
      @plant.user.score -= 1
      @plant.user.save!
    end

    private

    def plants_params
      params.require(:plant).permit(:user_id, :nickname, :photo, :age_in_days)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    def create
        @chatroom = Chatroom.find(params[:chatroom_id])
        @message = Message.new(message_params)
        @message.chatroom = @chatroom
        @message.user = current_user
        if @message.save
          ChatroomChannel.broadcast_to(
            @chatroom,
            render_to_string(partial: "message", locals: { message: @message })
          )
          redirect_to chatroom_path(@chatroom, anchor: "message-#{@message.id}")
        else
          render "chatrooms/show"
        end

      end

    private

    def message_params
        params.require(:message).permit(:content, :chatroom_id, :user_id)
    end
end

app/controllers/neighborhood_controller.rb
class NeighborhoodController < ApplicationController
  
  def index
    @users = User.all    
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude
      }
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @plants = Plant.where(user: current_user)
    @activity = Activity.new
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   

    def show
        @user = User.find(params[:id])    
    end

    private

    def users_params
        params.require(:user).permit(:first_name, :address, :email, :password, :photo)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end

app/views/activities/_new_activity_form.html.erb
<%= simple_form_for @activity do |f| %>
  <% f.input :plant_id, as: :hidden, input_html: { value: plant.id } %>
  <% f.input :task_id, as: :hidden, input_html: { value: task.id } %>
  <% f.object.plant_id = plant.id %>
  <% f.object.task_id = task.id %>
  <%# <% f.hidden_field :plant_id, value: plant.id %>
  <%# <%= f.hidden_field :task_id, value: task.id %>
  <%# <%= raise %>
  <%= f.submit "Fait!", class: 'btn-task mr-2' %>
<% end %>

app/views/chatrooms/index.html.erb
<% content_for :meta_title, "Chat" %>
<% content_for :meta_description, "Discutez avec votre voisins" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header-chatrooms">
    <h1 id="chat-title">Mes conversations</h1>
    <%= cl_image_tag current_user.photo.key, class: "avatar-bordered avatar-top-right dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Se déconnecter", destroy_user_session_path , class: "dropdown-item", method: :delete %>
    </div>
</div>

<div class="container mt-2">
  <% @chatrooms.each do |chatroom| %>
    <% messages = chatroom.messages.where.not(user_id: current_user).select(:user_id).distinct %>
    <% messages.each do |message| %>
      <div class="card-deck flex-row flex-nowrap content-user-chat">
        <%= link_to chatroom_path(chatroom.id), class:"avatar-click-to-message" do %>
          <div class="user-chat">
            <div class="user-photo-chat">
                <%= cl_image_tag message.user.photo.key, class:"user-photo-chat" %>
            </div>
            <div class="infos-user-chat">
              <div class="name-hour-chat">
                <h3 id="chat-name"><%= message.user.first_name %></h3>
              </div>
              <div class="last-message">
                <p><%= chatroom.messages.last.content %></p>
                <p><%= chatroom.messages.last.created_at.strftime("%H:%M") %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/chatrooms/show.html.erb
<% content_for :meta_title, "Messages" %>
<% content_for :meta_description, "Ecrivez votre message" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header-messages">
  <h1 id="title-chat">Discutez avec votre voisin</h1>
  <%#= @chatroom.messages.where.not(user_id: current_user).first.user.first_name %>
</div>

<%= link_to chatrooms_path do%>
  <i class="fas fa-angle-left bouton-back-header"></i>
<% end %>

<div class="container">
    <div class="chatroom">
        <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <% @chatroom.messages.each do |message| %>
            <div class="message-and-picture <%= "flex-row-reverse" if message.user == current_user %>">
              <%= cl_image_tag message.user.photo.key, class:"avatar-bordered community-avatar" %>
              <div class="message-container <%="my-message" if message.user_id == current_user.id %>" id="message-<%= message.id %>">
              <i class="author">
                  <span id="user-name"><%= message.user.first_name %></span>
                  <span id="chat-date"><%= message.created_at.strftime("%m %^b %H:%M") %></span>
              </i>
              <p id="chat-message"><%= message.content %></p>
              </div>
            </div>
        <% end %>
        </div>
    </div>
</div>

<div class="new-message">
    <%= simple_form_for [ @chatroom, @message ] do |f| %>
        <%= f.input :content, label: false, placeholder: "Ecrivez votre message", class:"my-message-encadre" %>
    <% end %>
</div>

app/views/garden/communities/classement.html.erb
<% content_for :meta_title, "Classement" %>
<% content_for :meta_description, "Classement général" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header-classement">
  <h1>Classement général</h1>
  <%= cl_image_tag current_user.photo.key, class: "avatar-bordered avatar-top-right" %>
</div>

<%= link_to communities_path do%>
  <i class="fas fa-angle-left bouton-back-header"></i>
<% end %>

<div class="container">
  <div class="podium-classement">
    <% counter = 0 %>
    <% until counter == 3 %>
      <div class="ranking-podium">
        <div class="podium">
          <div id= "position<%= counter %>">
            <p id="name<%= counter  %>" class="name-podium"> <%= @podium[counter].first_name %></p>
            <p id="score<%= counter  %>" class="score-podium"><%= @podium[counter].score %> points</p>
            <p id="photo<%= counter  %>"><%= cl_image_tag @podium[counter].photo.key, class: "photo-podium avatar-top-right" %></p>
          </div>
          <% counter += 1 %>
        </div>
      </div>
    <% end %>
  </div>

  <img src="https://www.pngitem.com/pimgs/m/47-475004_podium-clipart-award-winning-transparent-background-podium-png.png" width="350" class="image-podium">

  <hr>
  <%# <div class="container-ranking"> %>
    <div class="ranking">
      <p class="headers"><strong>Rang</strong></p>
      <p class="headers"><strong>Jardinier</strong></p>
      <p class="headers mr-2"><strong>Score</strong></p>
    </div>

    <%# Affiche les scores  %>
    <%# @order vient du controller. Array contennant des instances de user dans l'order asc des scores %>
    <% @ranking.each do |user| %>
      <%# <% user = User.find(position.id) %>
      <div class="ranking">
        <p id="position"><%= @ranking.index(user) + 4%> </p>
        <%# <% raise %>
        <p id="name"> <%= user.first_name %></p>
        <p id="score"><%= user.score %> points</p>
      </div>
    <% end %>

    <% if false %>
      <h1 id="header">Ta position</h1>
        <div class="ranking">
          <p class="headers">Rang</p>
          <p class="headers">Gardeneur</p>
          <p class="headers">Score</p>
        </div>

        <div class="ranking">
          <p id="position"><%= @order.index(current_user) + 1 %></p>
          <p id="name"> <%= @order.find(current_user.id).first_name %></p>
          <p id="score"><%= @order.find(current_user.id).score %> points</p>
        </div>
    <% end %>

  <%# </div> %>
</div>

app/views/garden/communities/index.html.erb
<% content_for :meta_title, "Communauté" %>
<% content_for :meta_description, "Plantes des voisins" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header-community">
  <%= link_to communities_classement_path do %>
    <i class="fas fa-medal link-to-classement"></i>
  <% end %>
  <h1>Community</h1>
  <%= cl_image_tag current_user.photo.key, class: "avatar-bordered avatar-top-right dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "Se déconnecter", destroy_user_session_path , class: "dropdown-item", method: :delete %>
  </div>
</div>

<div class="container-plants-cards-community">
  <% @plants.each do |plant| %>
    <div id ="content-user-plants-community" class="card-deck flex-row flex-nowrap">
      <%= cl_image_tag plant.photo.key, crop: :fill, id:"photo-user-plant-community" %>
      <div class="card-right-side">
        <div class="user-info-community">
          <%= cl_image_tag plant.user.photo.key, class: "avatar-bordered community-avatar" %>
          <%= plant.user.first_name %>

          <%= simple_form_for @chatroom do |f| %>
            <%= f.input :name, as: :hidden, input_html: { value: "Conversation avec #{plant.user}" } %>
            <%= button_tag type: 'submit', class:"bouton-chat" do %>
              <i class="far fa-comment-dots text-secondary user-chat-from-community"></i>
            <% end %>
          <% end %>
        </div>
        <div class="info-user-plant-community">
          <em><%= plant.nickname %></em> - <%= plant.plant_information.family %>
          <%creation_date = plant.created_at %>
          <% calcul_date = @now - creation_date  %>
          <% age_plant = calcul_date / 86400 %>
          <div class="plant-age text-secondary">
            <% age_plant_final = plant.age_in_days.to_i %>
            <% if age_plant_final == 0 %>
                Nouvelle pousse
            <% elsif age_plant_final > 1 %>
                <%= age_plant_final %> jours
            <% else %>
                <%= age_plant_final %> jour
            <% end %>
          </div>
          <div class="like-counter">
            <%= link_to upvote_plant_path(plant.id), method: :patch, remote: true, class:"text-decoration-none" do %>
              <i class="far fa-heart fa-lg like-bouton text-secondary"></i>
            <% end %>
            <%= link_to dislike_plant_path(plant.id), method: :patch, remote: true, class:"text-decoration-none d-none" do %>
              <i class="fas fa-heart fa-lg dislike-bouton text-danger"></i>
            <% end %>
            <span><%= plant.like_number %></span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/garden/plants/index.html.erb
<% content_for :meta_title, "Mes plantes" %>
<% content_for :meta_description, "Liste des plantes" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header">
  <h1>My garden</h1>
  <%= cl_image_tag current_user.photo.key, class: "avatar-bordered avatar-top-right dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "Se déconnecter", destroy_user_session_path , class: "dropdown-item", method: :delete %>
  </div>
</div>

<div class="container-plants-cards">
  <% @user_plants.each do |user_plant| %>
    <div id ="content-user-plants" class="card-deck flex-row flex-nowrap">
      <a href="/plants/<%= user_plant.id %>">
      <div class="img-info-user-plant">
        <%= cl_image_tag user_plant.photo.key, crop: :fill, id:"photo-user-plant" %>
        <div class="info-user-plant">
          <li id="nickname-list-user-plant"><%= user_plant.nickname %></li>
          <%creation_date = user_plant.created_at %>
          <% calcul_date = @now - creation_date  %>
          <% age_plant = calcul_date / 86400 %>
          <div class="plant-age">
            <% age_plant_final = user_plant.age_in_days.to_i %>
            <% if age_plant_final == 0 %>
                Nouvelle pousse
            <% elsif age_plant_final > 1 %>
                <%= age_plant_final %> jours
            <% else %>
                <%= age_plant_final %> jour
            <% end %>
          </div>
        </div>
      </div>
      </a>
    </div>
  <% end %>
  <%= link_to new_plant_path do %>
    <div class="bouton-add-a-plant floating-bouton">
      <i class="fas fa-plus icon-add-a-plant"></i>
    </div>
  <% end %>
</div>


 <%# <%= image_tag("test-jardiniere-copie.png", id: "jardiniere-user-plant") %>

app/views/garden/plants/new.html.erb
<% content_for :meta_title, "Créer une plante" %>
<% content_for :meta_description, "Ajouter une nouvelle plante" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-new-plant">
  <%= link_to plants_path do %>
    <i class="fas fa-angle-left bouton-back"></i>
  <% end %>
  <h1 id="title-form-new-plant">Ma plante</h1>
</div>

<div class="container">
  <div class="form-new-plant">
      <%= simple_form_for [ @plant ] do |f| %>
          <label id="photo-new-plant", class="border">
          <i id="icone-add-photo", class="fas fa-seedling fa-2x navbar-icon"></i>
          <i id="icone-app-photo" class="fas fa-camera"></i>
              <div class="d-none">
                <%= f.input :photo, as: :file, label: false %>
              </div>

          </label>
          <div id="preview">

          </div>
          <div class="infos-form-plant-new">
              <%= f.input :nickname, label: false, placeholder: "Surnom", input_html: { class: 'champ-form' } %>
              <%= f.input :plant_information, label: 'Type de plante', collection: @plant_infos , prompt: "Selectionne le type de ta plante" %>
              <%= f.input :age_in_days, label: "Date de naissance", hint: "Approximativement, t'inquiète", as: :date, discard_day: true, html5: true%>

          </div>
          <%= f.submit "Créer ma plante", id:"btn-form-new-plant" %>
      <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
    <span><%= message.user.first_name %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/neighborhood/index.html.erb
<h1>Neighborhood#index</h1>
<p>Find me in app/views/neighborhood/index.html.erb</p>

<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/tasks/index.html.erb
<% content_for :meta_title, "To Do lists" %>
<% content_for :meta_description, "Tâches quotidiennes" %>
<%# <% content_for :meta_image, cl_image_path(@garden.photo.path) %>

<div class="top-page-header mb-1">
  <h1>To-do liste</h1>
  <%= cl_image_tag current_user.photo.key, class: "avatar-bordered avatar-top-right dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
    <%= link_to "Se déconnecter", destroy_user_session_path , class: "dropdown-item", method: :delete %>
  </div>
</div>

<div class="container">
  <% counter = 0 %>
  <% while counter < 4 do %>
    <div class="date-bloc">
      <% dayDate = DateTime.now + counter.day%>
      <div class="collapse-date" data-toggle="collapse" href="#collapseExample<%= counter %>" role="button" <%="aria-expanded=true" if counter == 0%> <%="aria-expanded=false" if counter != 0%> aria-controls="collapseExample">
        <h4 class="date-task"> <%= dayDate.strftime("%A %-d") %> </h4>
        <i class="fas fa-caret-down"></i>
      </div>
      <div class="tasks-date-block collapse <%="show" if counter == 0%>" id="collapseExample<%= counter %>">
        <% @plants.each do |plant| %>
          <div class="plants-tasks-block">
            <% plant.tasks.each do |task| %>
              <% plant_real_age = plant.age_in_days + counter %>
              <% if ((plant_real_age - task.intervalle) % task.intervalle == 0) %>
                <div class="tache-block">
                  <div class="tache-block-left">
                    <%= cl_image_tag plant.photo.key, class: "plant-photo-to-do mr-3", width: "70px", height: "70px"%>
                    <div class="tache-block-middle">
                      <span class="task-name-to-do"><%= task.name %></span>
                      <span class="nickname-sober"><%= plant.nickname %></span>
                    </div>
                  </div>
                  <div class="tache-block-right">
                    <p>+ <%= task.score %></p>
                    <%= simple_form_for @activity do |f| %>
                      <%= f.input :plant_id, as: :hidden, input_html: { value: plant.id } %>
                      <%= f.input :task_id, as: :hidden, input_html: { value: task.id } %>
                      <%= f.submit "Fait", class: 'btn-task mr-2', id: 'create-activity' %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <% counter += 1 %>
  <% end %>
</div>